object Version {
    const val agp = "8.4.1"
    const val kotlin = "1.9.0"
    const val coreKtx = "1.13.1"
    const val junit = "4.13.2"
    const val junitVersion = "1.1.5"
    const val espressoCore = "3.5.1"
    const val lifecycleRuntimeKtx = "2.8.0"
    const val activityCompose = "1.9.0"
    const val composeBom = "2023.08.00"
    const val hiltNavigationCompose = "1.2.0"
    const val navigationCompose = "2.7.7"
    const val coilCompose = "2.6.0"
    const val retrofit ="2.9.0"
    const val moshiKotlin = "1.9.3"
}